# Multiple Jobs with Dependencies
# This workflow demonstrates how to create multiple jobs and define dependencies between them

name: Multiple Jobs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run lint
      
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint  # This job waits for 'lint' to complete
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm test
      
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint, test]  # This job waits for both 'lint' and 'test' to complete
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run build
      
  deploy:
    name: Deploy (Simulated)
    runs-on: ubuntu-latest
    needs: build  # This job waits for 'build' to complete
    
    steps:
    - name: Simulate deployment
      run: |
        echo "Deploying application..."
        echo "Deployment completed successfully!"
