# Artifacts
# This workflow demonstrates how to upload and download artifacts between jobs

name: Artifacts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests with coverage
      run: npm test -- --coverage
      
    - name: Create build artifacts
      run: |
        mkdir -p build
        echo "Build completed at $(date)" > build/build-info.txt
        cp package.json build/
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/
        retention-days: 7
        
  use-artifacts:
    name: Download and Use Artifacts
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: ./downloaded-coverage
        
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: ./downloaded-build
        
    - name: Display artifact contents
      run: |
        echo "Coverage report files:"
        ls -la ./downloaded-coverage
        echo ""
        echo "Build artifact files:"
        ls -la ./downloaded-build
        echo ""
        echo "Build info:"
        cat ./downloaded-build/build-info.txt
