# Conditional Execution
# This workflow demonstrates various conditional execution patterns

name: Conditional Execution

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  conditional-steps:
    name: Conditional Steps
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    # Run only on push events
    - name: Run on push only
      if: github.event_name == 'push'
      run: echo "This step runs only on push events"
      
    # Run only on pull requests
    - name: Run on PR only
      if: github.event_name == 'pull_request'
      run: echo "This step runs only on pull request events"
      
    # Run only on main/master branch
    - name: Run on main branch only
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: echo "This step runs only on main/master branch"
      
    # Run tests
    - name: Run tests
      id: tests
      run: npm test
      continue-on-error: true
      
    # Run only if tests succeeded
    - name: On test success
      if: steps.tests.outcome == 'success'
      run: echo "✅ Tests passed successfully!"
      
    # Run only if tests failed
    - name: On test failure
      if: steps.tests.outcome == 'failure'
      run: echo "❌ Tests failed!"
      
    # Always run (even if previous steps fail)
    - name: Always run
      if: always()
      run: echo "This step always runs regardless of previous step outcomes"
      
  conditional-job:
    name: Conditional Job (runs on push only)
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Job runs conditionally
      run: echo "This entire job runs only on push events"
      
  matrix-with-conditions:
    name: Matrix with Conditions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
      
    - name: Run special test for Node 20
      if: matrix.node-version == 20
      run: echo "Running special tests for Node 20"
      
    - name: Run tests
      run: npm test
